### ISSUE TITLE
Bad encoding of É character

### ISSUE THREAD

**Issue by dsprenkels** [thomwiggers/onebot#42]
On `#ru`, `OneBot` failed to encode the title of 'Nightwish  – Élan' correctly:

```
[16:55:34] <+Daan> .np
[16:55:36] <OneBot> Daan is now playing “Nightwish – Ã‰lan”.
```

**Comment by thomwiggers** [comment]
Not a bug, this track is reported as ` Ã‰lan` by Last.fm. Their API **sucks**
